### ISSUE TITLE
Can't run the GAS debugger

### ISSUE THREAD

**Issue by neilbmclaughlin** [simula-innovation/qunit#2]
I have copied the 'QUnit for GAS' script project to identify a problem I'm having with running the debugger.

https://script.google.com/a/macros/echelon-solutions.co.uk/d/MY_EOuwHBPLDV54zTB1_HOZBe8J7HHPDf/edit

If I try and debug even a simple function (eg function f() { Logger.log('test') }) then I get a 'We're sorry, a server error occurred. Please wait a bit and try again.' error.

There seems to be a problem loading qunit.js.gs, it gets as far as initialisation on line 13 but then seems to throw an unhandled exception when trying to do stuff with session state but I can't see what the problem is.

Any thoughts as without the debugger working I'm stuck.

Thanks

Neil

**Comment by adapi** [comment]
This is a GAS debugger issue, and should be reported to the [GAS issue list](https://code.google.com/p/google-apps-script-issues/issues/list) instead. Those uninformative "We're sorry, a server error occurred" error messages that sometimes pop up when you add breakpoints and try to step into them are as mysterious to me as they are for you, and were one of the reasons why I adapted QUnit for GAS in the first place, so I didn't have to use the debugger anymore. Sorry, but I can't help you on this one.
